FROM python:3.9.7

WORKDIR /YpoxreotikiErgasia23_e20113_Nikolaidis_Nearchos

COPY . /YpoxreotikiErgasia23_e20113_Nikolaidis_Nearchos/

RUN pip install -r requirements.txt
EXPOSE 5000

CMD python ./app.py
